openapi: 3.1.0
info:
  title: Aiera Events API
  description: API for accessing events data from Aiera
  version: 1.0.0
servers:
  - url: https://premium.aiera.com/api
security:
  - ApiKeyAuth: []
paths:
  /events-v2/person/{person_id}:
    get:
      operationId: getPerson
      description: Retrieves a person using a person id.
      summary: Retrieves a single person
      parameters:
        - name: person_id
          in: path
          required: true
          schema:
            type: integer
          description: person id to get the speaker details
      responses:
        "200":
          description: Successfully retrieved the person details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        "404":
          description: Person not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:

    Person:
      type: object
      properties:
        event_id:
          type: integer
        question:
          type: object
          properties:
            summary:
              type: object
              properties:
                extract:
                  type: string
                abridged:
                  type: string
            speakers:
              type: array
              items:
                type: object
                properties:
                  person_id:
                    type: integer
                  speaker_name:
                    type: string
            linguistics:
              type: object
              properties:
                tonal:
                  type: number
                topics:
                  type: array
                  items:
                    type: object
                    properties:
                      topic:
                        type: string
                      position:
                        type: integer
                      topic_id:
                        type: integer
                sentiments:
                  type: object
                  properties:
                    median:
                      type: number
                    average:
                      type: number
                    maximum:
                      type: number
                    minimum:
                      type: number
        answer:
          type: object
          properties:
            summary:
              type: object
              properties:
                extract:
                  type: string
                abridged:
                  type: string
            speakers:
              type: array
              items:
                type: object
                properties:
                  person_id:
                    type: integer
                  speaker_name:
                    type: string
            linguistics:
              type: object
              properties:
                tonal:
                  type: number
                topics:
                  type: array
                  items:
                    type: object
                    properties:
                      topic:
                        type: string
                      position:
                        type: integer
                      topic_id:
                        type: integer
                sentiments:
                  type: object
                  properties:
                    median:
                      type: number
                    average:
                      type: number
                    maximum:
                      type: number
                    minimum:
                      type: number
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
